---
version: 2
models:
- name: "env_uitesting_shared_child_model_1"
  columns:
  - name: "c_tinyint"
    dataType:
      type: "TinyInt"
  - name: "c_smallint"
    dataType:
      type: "SmallInt"
  - name: "c_int"
    dataType:
      type: "Integer"
  - name: "c_bigint"
    dataType:
      type: "Bigint"
  - name: "c_float"
    dataType:
      type: "Float"
  - name: "c_double"
    dataType:
      type: "Float"
  - name: "c_string"
    dataType:
      type: "String"
  - name: "c_boolean"
    dataType:
      type: "Boolean"
  - name: "c_array"
    dataType:
      type: "Array"
      dataType:
        type: "String"
  - name: "c_struct"
    dataType:
      type: "Struct"
      fields:
      - name: "city"
        dataType:
          type: "String"
      - name: "state"
        dataType:
          type: "String"
      - name: "pin"
        dataType:
          type: "Bigint"
  - name: "c_test"
    dataType:
      type: "String"
