---
version: 2
snapshots:
- name: "snapshot_sanity_test_1"
  columns:
  - name: "c_float"
    dataType:
      type: "Float"
  - name: "dbt_valid_to"
    dataType:
      type: "Float"
  - name: "dbt_updated_at"
    dataType:
      type: "Float"
  - name: "c_boolean"
    dataType:
      type: "Boolean"
  - name: "c_smallint"
    dataType:
      type: "SmallInt"
  - name: "c_array"
    dataType:
      type: "Array"
      dataType:
        type: "String"
  - name: "c_double"
    dataType:
      type: "Double"
  - name: "c_struct"
    dataType:
      type: "Struct"
      fields:
      - name: "city"
        dataType:
          type: "String"
      - name: "state"
        dataType:
          type: "String"
      - name: "pin"
        dataType:
          type: "Bigint"
  - name: "dbt_valid_from"
    dataType:
      type: "Float"
  - name: "c_bigint"
    dataType:
      type: "Bigint"
  - name: "c_timestamp"
    dataType:
      type: "Timestamp"
  - name: "c_int"
    dataType:
      type: "Integer"
  - name: "dbt_scd_id"
    dataType:
      type: "String"
  - name: "c_string"
    dataType:
      type: "String"
  - name: "c_tinyint"
    dataType:
      type: "TinyInt"
  tests: []
