---
version: 2
models:
- name: "env_uitesting_shared_useallmodel_1"
  columns:
  - name: "c_tinyint"
    tests:
    - unique:
        config:
          fail_calc: "count(*)"
          warn_if: ""
          where: "c_int != 2"
          severity: "warn"
          store_failures: true
          limit: 2
    - accepted_values:
        config:
          fail_calc: "count(*)"
        values:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
        - "11"
        - "12"
    - accepted_values:
        config:
          fail_calc: "count(*)"
        values:
        - "100"
        - "200"
    dataType:
      type: "TinyInt"
  - name: "c_smallint"
    tests:
    - relationships:
        config:
          fail_calc: "count(*)"
          warn_if: ""
          where: "c_string IS NOT NULL"
          store_failures: true
          limit: 2
        to: "source(\"alias_son_hive_metastore_qa_database\", \"all_type_partitioned\"\
          )"
        field: "c_smallint"
    dataType:
      type: "SmallInt"
  - name: "c_int"
    dataType:
      type: "Integer"
  - name: "c_bigint"
    dataType:
      type: "Bigint"
  - name: "c_float"
    dataType:
      type: "Float"
  - name: "c_double"
    dataType:
      type: "Float"
  - name: "c_string"
    tests:
    - not_null:
        config:
          fail_calc: "count(*)"
          severity: "error"
    dataType:
      type: "String"
  - name: "c_boolean"
    dataType:
      type: "Boolean"
  - name: "c_array"
    dataType:
      type: "Array"
      dataType:
        type: "String"
  - name: "c_struct"
    dataType:
      type: "Struct"
      fields:
      - name: "city"
        dataType:
          type: "String"
      - name: "state"
        dataType:
          type: "String"
      - name: "pin"
        dataType:
          type: "Bigint"
  tests:
  - new_multi_model_not_null:
      column_name_model_2: "c_tinyint"
      column_name_model_1: "c_tinyint"
      model1: "env_uitesting_main_model_databricks_2"
      config:
        fail_calc: "count(*)"
        warn_if: ""
        where: "c_double IS NOT NULL AND c_int BETWEEN -10000 AND 10000"
      column_name_mode1_2: "c_int"
      column_name_mode1_1: "c_int"
  - not_null:
      config:
        fail_calc: "count(*)"
      column_name: "c_struct.state"
